/*
* generated by Xtext
*/
package org.eclipse.net4j.tools.workingset.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class DslTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
