/*
 * generated by Xtext
 */
package org.eclipse.net4j.tools.workingset;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DslRuntimeModule extends org.eclipse.net4j.tools.workingset.AbstractDslRuntimeModule
{

}
