
/*
 * generated by Xtext
 */
 
package org.eclipse.net4j.tools.workingset.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class DslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.eclipse.net4j.tools.workingset.ui.internal.DslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.eclipse.net4j.tools.workingset.ui.internal.DslActivator.getInstance().getInjector("org.eclipse.net4j.tools.workingset.Dsl");
	}
	
}
