<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dbgen"
    nsURI="http://www.eclipse.org/net4j/dbgen.ecore" nsPrefix="org.eclipse.emf.cdo.dbgen">
  <eClassifiers xsi:type="ecore:EEnum" name="ColumnType">
    <eLiterals name="BOOLEAN" value="16"/>
    <eLiterals name="BIT" value="-7"/>
    <eLiterals name="TINYINT" value="-6"/>
    <eLiterals name="SMALLINT" value="5"/>
    <eLiterals name="INTEGER" value="4"/>
    <eLiterals name="BIGINT" value="-5"/>
    <eLiterals name="FLOAT" value="6"/>
    <eLiterals name="REAL" value="7"/>
    <eLiterals name="DOUBLE" value="8"/>
    <eLiterals name="NUMERIC" value="2"/>
    <eLiterals name="DECIMAL" value="3"/>
    <eLiterals name="CHAR" value="1"/>
    <eLiterals name="VARCHAR" value="12"/>
    <eLiterals name="LONGVARCHAR" value="-1"/>
    <eLiterals name="DATE" value="91"/>
    <eLiterals name="TIME" value="92"/>
    <eLiterals name="TIMESTAMP" value="93"/>
    <eLiterals name="BINARY" value="-2"/>
    <eLiterals name="VARBINARY" value="-3"/>
    <eLiterals name="LONGVARBINARY" value="-4"/>
    <eLiterals name="BLOB" value="2004"/>
    <eLiterals name="CLOB" value="2005"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Database">
    <eOperations name="getTable" eType="#//Table">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="addTable" eType="#//Table">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tables" upperBound="-1"
        eType="#//Table" containment="true" eOpposite="#//Table/database"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Table">
    <eOperations name="getPrimaryIndex" eType="#//Index"/>
    <eOperations name="getColumn" eType="#//Column">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="addColumn" eType="#//Column">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="type" eType="#//ColumnType"/>
      <eParameters name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="constraint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="addColumn" eType="#//Column">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="type" eType="#//ColumnType"/>
      <eParameters name="constraint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="addColumn" eType="#//Column">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="type" eType="#//ColumnType"/>
      <eParameters name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="addColumn" eType="#//Column">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="type" eType="#//ColumnType"/>
    </eOperations>
    <eOperations name="getIndex" eType="#//Index">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="addIndex" eType="#//Index">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="type" eType="#//IndexType"/>
    </eOperations>
    <eOperations name="addSimpleIndex" eType="#//Index">
      <eParameters name="columnName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="indexType" eType="#//IndexType"/>
    </eOperations>
    <eOperations name="addCompoundIndex" eType="#//Index">
      <eParameters name="columnNames" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="indexType" eType="#//IndexType"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="database" lowerBound="1"
        eType="#//Database" eOpposite="#//Database/tables"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1"
        eType="#//Column" containment="true" eOpposite="#//Column/table"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="indices" upperBound="-1"
        eType="#//Index" containment="true" eOpposite="#//Index/table"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Column">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="table" lowerBound="1" eType="#//Table"
        eOpposite="#//Table/columns"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ColumnType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Index">
    <eOperations name="getColumn" eType="#//Column">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="addColumn" eType="#//Column">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="addColumn" eType="#//Column">
      <eParameters name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="table" lowerBound="1" eType="#//Table"
        eOpposite="#//Table/indices"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1"
        eType="#//Column"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//IndexType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IndexType">
    <eLiterals name="NON_UNIQUE"/>
    <eLiterals name="UNIQUE" value="1"/>
    <eLiterals name="PRIMARY" value="2"/>
  </eClassifiers>
</ecore:EPackage>
